name: 'Get Description From README Action'
description: 'GitHub Action to get description from README.'
author: 'rtvu'

branding:
  icon: 'info'
  color: 'gray-dark'

inputs:
  readme:
    description: 'Path to README'
    required: false
    default: 'README.md'

outputs:
  description:
    description: 'README''s description'
    value: ${{ steps.get-description.outputs.description }}

runs:
  using: 'composite'
  steps:
    -
      name: 'Get description'
      id: get-description
      shell: python3 -u {0} ${{ inputs.readme }}
      run: |
        import argparse
        import os
        import sys

        def get_description(readme_path):
            try:
                description = ''
                with open(readme_path, 'r') as readme:
                    for line in readme:
                        line = line.strip()
                        if len(line) > 0 and line[0] != '#':
                            description = line
                            break
                output_path = os.getenv('GITHUB_OUTPUT')
                with open(output_path, 'a') as output:
                    output.write(f'description={description}')
            except Exception as exception:
                sys.exit(exception)

        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument('readme_path', nargs='?', type=str, help='Path to README', default='README.md')
            args = parser.parse_args()
            get_description(readme_path=args.readme_path)

        if __name__ == '__main__':
            main()
